-- +goose Up
CREATE TABLE IF NOT EXISTS tdata (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shortURL VARCHAR(20) NOT NULL,
    originalURL VARCHAR(128) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_urls_short_url ON tdata (shortURL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tdata_originalurl_unique ON tdata (originalURL);

-- +goose Down
DROP INDEX IF EXISTS idx_tdata_originalurl_unique;
DROP TABLE IF EXISTS tdata;