package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

const generateResetComment = "generate:reset"

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	// Начинаем сканирование с корневой директории проекта
	return filepath.Walk("../..", func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Пропускаем директории и не-Go файлы
		if info.IsDir() || !strings.HasSuffix(info.Name(), ".go") {
			return nil
		}

		return processGoFile(path, strings.TrimSuffix(info.Name(), ".go"))
	})
}

func processGoFile(filePath string, pack string) error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("failed to parse %s: %w", filePath, err)
	}

	// Находим все структуры с комментарием // generate:reset
	structsToReset := findStructsWithResetComment(file)
	if len(structsToReset) == 0 {
		return nil // Нет структур для обработки в этом файле
	}

	// Определяем директорию пакета и имя файла для генерации
	packageDir := filepath.Dir(filePath)
	genFileName := filepath.Join(packageDir, "reset.gen.go")

	// Генерируем код для методов Reset()
	resetCode := generateResetMethods(structsToReset, file, pack)

	// Записываем сгенерированный код
	return writeResetFile(genFileName, resetCode)
}

func findStructsWithResetComment(file *ast.File) []string {
	var structs []string

	ast.Inspect(file, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok || typeSpec.Type == nil {
			return true
		}

		_, ok = typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		// Проверяем комментарии перед объявлением структуры
		if hasGenerateResetComment(typeSpec.Doc) {
			structs = append(structs, typeSpec.Name.Name)
			return true
		}

		// Дополнительно проверяем комментарии рядом с узлом в общем списке
		if hasCommentNearNode(file, typeSpec, generateResetComment) {
			structs = append(structs, typeSpec.Name.Name)
			return true
		}
		return false
	})

	return structs
}

func hasGenerateResetComment(commentGroup *ast.CommentGroup) bool {
	if commentGroup == nil {
		return false
	}

	for _, comment := range commentGroup.List {
		text := strings.TrimSpace(comment.Text)
		// Убираем префикс //
		if strings.HasPrefix(text, "//") {
			text = strings.TrimPrefix(text, "//")
			text = strings.TrimSpace(text)
		}
		if text == "generate:reset" {
			return true
		}
	}
	return false
}

func hasCommentNearNode(file *ast.File, node ast.Node, targetComment string) bool {
	nodePos := node.Pos()

	for _, commentGroup := range file.Comments {
		for _, comment := range commentGroup.List {
			commentText := strings.TrimSpace(comment.Text)
			if strings.HasPrefix(commentText, "//") {
				commentText = strings.TrimPrefix(commentText, "//")
				commentText = strings.TrimSpace(commentText)
			}

			if commentText == targetComment {
				// Проверяем, что комментарий находится непосредственно перед узлом
				if comment.End() <= nodePos {
					return true
				}
			}
		}
	}
	return false
}

func generateResetMethods(structNames []string, file *ast.File, pack string) string {
	var sb strings.Builder

	sb.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	sb.WriteString(fmt.Sprintf("package %s\n\n", pack))

	for _, structName := range structNames {
		sb.WriteString(generateResetMethod(structName, file))
		sb.WriteString("\n")
	}

	return sb.String()
}

func generateResetMethod(structName string, file *ast.File) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", structName))

	// Получаем поля структуры для генерации кода сброса
	fieldsCode := generateFieldsResetCode(structName, file)
	sb.WriteString(fieldsCode)

	sb.WriteString("}\n")
	return sb.String()
}

func generateFieldsResetCode(structName string, file *ast.File) string {
	var sb strings.Builder

	// Находим определение структуры в AST
	var structType *ast.StructType
	ast.Inspect(file, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok || typeSpec.Name.Name != structName {
			return true
		}

		var ok2 bool
		structType, ok2 = typeSpec.Type.(*ast.StructType)
		if ok2 {
			return false // Нашли, прекращаем обход
		}
		return true
	})

	if structType == nil {
		return "\t// Error: structure " + structName + " not found in AST\n"
	}

	// Обрабатываем каждое поле структуры
	for _, field := range structType.Fields.List {
		if field.Names == nil {
			continue // Анонимные поля пропускаем
		}

		for _, name := range field.Names {
			fieldCode := generateFieldResetCode(name.Name, field.Type)
			sb.WriteString(fieldCode)
		}
	}

	return sb.String()
}

func writeResetFile(fileName, code string) error {
	// Создаём файл
	file, err := os.Create(fileName)
	if err != nil {
		return fmt.Errorf("failed to create %s: %w", fileName, err)
	}
	defer file.Close()

	_, err = file.WriteString(code)
	if err != nil {
		return fmt.Errorf("failed to write %s: %w", fileName, err)
	}

	fmt.Printf("Generated reset methods in %s\n", fileName)
	return nil
}

func generateFieldResetCode(fieldName string, fieldType ast.Expr) string {

	switch t := fieldType.(type) {

	case *ast.Ident:
		// Примитивные типы и именованные типы
		typeName := t.Name

		switch typeName {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "complex64", "complex128":
			return fmt.Sprintf("\ts.%s = 0\n", fieldName)

		case "string":
			return fmt.Sprintf("\ts.%s = \"\"\n", fieldName)

		case "bool":
			return fmt.Sprintf("\ts.%s = false\n", fieldName)

		default:
			// Для пользовательских типов проверяем, есть ли метод Reset()
			return fmt.Sprintf("\tif s.%s != nil { s.%s.Reset() }\n", fieldName, fieldName)
		}

	case *ast.ArrayType:
		// Слайсы и массивы
		if t.Len == nil {
			// Это слайс
			return fmt.Sprintf("\ts.%s = s.%s[:0]\n", fieldName, fieldName)
		} else {
			// Это массив — просто обнуляем
			return fmt.Sprintf("\ts.%s = [0]%s{}\n", fieldName, getTypeString(t.Elt))
		}

	case *ast.MapType:
		// Мапы
		return fmt.Sprintf("\tclear(s.%s)\n", fieldName)

	case *ast.StarExpr:
		// Указатели
		return fmt.Sprintf("\tif s.%s != nil { s.%s = nil }\n", fieldName, fieldName)

	case *ast.StructType:
		// Вложенные анонимные структуры
		return fmt.Sprintf("\ts.%s = %s{}\n", fieldName, getStructTypeString(t))

	default:
		return ""
	}
}

// Получает строковое представление типа для использования в коде
// func getTypeString(expr ast.Expr) string {
// 	switch t := expr.(type) {
// 	case *ast.Ident:
// 		return t.Name
// 	case *ast.StarExpr:
// 		return "*" + getTypeString(t.X)
// 	default:
// 		return "unknown"
// 	}
// }

func getTypeString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		baseType := getTypeString(t.X)
		if baseType == "File" {
			return "*os.File"
		}
		return "*" + baseType
	default:
		return "nil"
	}
}

// Формирует строковое представление вложенной структуры
func getStructTypeString(structType *ast.StructType) string {
	fields := []string{}
	for _, field := range structType.Fields.List {
		if field.Names != nil {
			for _, name := range field.Names {
				fields = append(fields, name.Name)
			}
		}
	}
	return fmt.Sprintf("struct{%s}", strings.Join(fields, " "))
}
