// Code generated by go generate; DO NOT EDIT.

package audit

func (s *AuditEvent) Reset() {
	s.TS = 0
	s.Action = ""
	s.UserID = ""
	s.URL = ""
}

func (s *FileAuditSubscriber) Reset() {
	if s.file != nil { s.file = nil }
}

func (s *RemoteAuditSubscriber) Reset() {
	if s.client != nil { s.client = nil }
	s.url = ""
}

func (s *AuditManager) Reset() {
	s.subscribers = s.subscribers[:0]
}

